//------------------------------------------------------------------------
// Copyright(c) 2023 AFSAudio.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Stuff2.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Stuff2 VST3 (64Bit)"
#else
#define stringFileDescription	"Stuff2 VST3"
#endif
#define stringCompanyName		"AFSAudio\0"
#define stringLegalCopyright	"Copyright(c) 2023 AFSAudio."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
